### PR TITLE
Include external clusters, instructions for supplying own database and check at the end

### PR DESCRIPTION
**Pull request by blue-moon22**
- Including GPS external clusters here
- Better instructions for supplying your own database and external clusters (haven't asked for zip though because I think it might be better for user to unzip themselves to check they have the storage?)
- Ran ./tests/regression_tests.sh and it passed. 
- Include note in README about not using the same sample IDs as in the GPS database
- Included a message at the end which tests for the number of expected assignments/samples and a Success or Fail (unexpected number of samples)

### CODE REVIEW

**Comment by blue-moon22** [comment]
Hi @kumarnaren - made changes (and including those we discussed today), do:
```
git fetch
git checkout fix/get_GPSC
git pull origin fix/get_GPSC
```
git fetch gets new data from the repo, checkout goes to the branch and git pull downloads the latest version of the branch

**Comment by blue-moon22** [comment]
Fixed the output comment and outputing the right cluster file.
do:
`git pull origin fix/get_GPSC` to get the latest changes

**Comment by blue-moon22** [comment]
Included latest changes, ready to test

**Comment by kumarnaren** [comment]
Just tested it, seems all good to me, hurray!!! we are officially ready for the first version !!! well done Vicky great effort..I am so happy

**Pull request merged**
